spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 2084team
#    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://121.41.229.179:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://172.16.75.201:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: 2084team
    password: 2084team
    host: 172.16.75.192
    port: 5672
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 172.16.75.192
    database: 0
    port: 6379
  cache:
    cache-names: menus_cache
server:
  port: 8182
  compression:
    enabled: true
fastdfs:
  nginx:
    host: 127.0.0.1